<?php

return [
    'en' => [
        '0'=> "Couldn't find your account|The account is not registered in the system. Please ensure the username you entered is correct.",
        '1'=> 'Invalid parameter|Please complete all required fields.',
        '2'=> "You've been successfully logged out",
        '3'=> 'Success',
        '4'=> 'The current application version is outdated, please reinstall from the Play Store to get the latest version.',
        '5'=> 'Your account needs to be confirmed|Please confirm your account by following the provided instructions',
        '6'=> 'Invalid password|The password is incorrect, please make sure you enter the correct password.',
        '7'=> 'Request failed|Please check your internet connection and try again.',
        '8'=> 'Detected using a different device|You are detected using a different phone than the one registered in the system. Please log in using the appropriate phone or contact the help desk.',
        '9'=> 'You do not have access|Your account does not have access to this application. For further assistance, please contact the help desk.',
        '10'=> 'Your request does not match|Please ensure that the data you provided follows the correct format.',
        '11'=> 'Please check your WhatsApp',
        '12'=> 'No account found with that email address',
        '13'=> 'Please check your email',
        '14'=> 'The OTP code has been sent to your email',
        '15'=> 'Failed to send OTP code to email|The OTP code could not be sent to your email. Please check your internet connection or use an alternative option to receive the OTP code.',
        '16'=> 'The OTP code has been sent to your Whatsapp',
        '17'=> 'Failed to send OTP code to Whatsapp|The OTP code could not be sent to your Whatsapp. Please check your internet connection or use an alternative option to receive the OTP code.',
        '18'=> 'Your password use special character',
        '19'=> 'Password has been reset successfully',
        '20'=> 'Your old password was entered incorrectly',
        '21'=> 'The new password cannot be the same as the old password',
        '22'=> 'Password changed successfully',
        '23'=> 'Your login session has expired, please log in again to continue',
        '24'=> 'Your session is active',
        '25'=> 'Your accound has been confirmed',
        '26'=> 'FAILED TO PROCESS|An error occurred. Please contact the help desk for further assistance.',

        ],
    'id' => [
        '0'=> 'Akun tidak terdaftar|Akun tidak terdaftar pada sistem, pastikan username yang Anda masukkan sudah benar.',
        '1'=> 'Parameter tidak sesuai|Mohon lengkapi form isian untuk melanjutkan.',
        '2'=> 'Anda berhasil keluar',
        '3'=> 'Berhasil',
        '4'=> 'Aplikasi Anda telah usang, mohon install ulang dari Play Store untuk mendapatkan versi terbaru',
        '5'=> 'Akun Anda perlu dikonfirmasi|Mohon konfirmasikan akun Anda dengan mengikuti instruksi yang telah diberikan.',
        '6'=> 'Kata sandi tidak sesuai|Kata sandi tidak sesuai, pastikan Anda menuliskan kata sandi yang benar.',
        '7'=> 'Permintaan gagal|Terdapat kesalahan teknis, harap periksa koneksi internet Anda dan coba lagi.',
        '8'=> 'Perangkat tidak sesuai|Anda terdeteksi menggunakan ponsel yang berbeda dengan yang terdaftar pada sistem. Silakan masuk menggunakan ponsel yang sesuai atau hubungi help desk.',
        '9'=> 'Anda tidak memiliki akses|Akun Anda tidak memiliki akses ke aplikasi ini. Untuk bantuan lebih lanjut, harap hubungi help desk.',
        '10'=> 'Permintaan Anda Tidak Sesuai|Pastikan data yang Anda kirimkan sesuai dengan format yang benar.',
        '11'=> 'Mohon periksa aplikasi Whatsapp Anda',
        '12'=> 'Tidak ditemukan akun dengan alamat email tersebut',
        '13'=> 'Mohon periksa email Anda',
        '14'=> 'Kode OTP telah dikirimkan ke email Anda',
        '15'=> 'Email gagal terkirim|Pengiriman kode OTP ke email gagal. Mohon periksa koneksi internet Anda atau gunakan opsi lain untuk menerima kode OTP.',
        '16'=> 'Kode OTP telah dikirimkan ke Whatsapp Anda',
        '17'=> 'Whatsapp gagal terkirim|Pengiriman kode OTP ke Whatsapp gagal. Mohon periksa koneksi internet Anda atau gunakan opsi lain untuk menerima kode OTP.',
        '18'=> 'Kata sandi Anda menggunakan karakter khusus',
        '19'=> 'Pengaturan ulang kata sandi berhasil',
        '20'=> 'Kata sandi lama yang Anda masukkan tidak sesuai',
        '21'=> 'Kata sandi baru tidak boleh sama dengan kata sandi lama',
        '22'=> 'Ubah kata sandi berhasil',
        '23'=> 'Sesi login Anda telah berakhir, silakan masuk kembali untuk melanjutkan',
        '24'=> 'Sesi Anda aktif',
        '25'=> 'Konfirmasi akun berhasil',
        '26'=> 'GAGAL PROSES|Terjadi kesalahan, silakan hubungi help desk untuk informasi lebih lanjut.',


        ]
];
